# Codificación de variables categóricas

---
Nombre: **Alan Jesús Hernández Soto** \
Carrera: **Ingeniería Financiera** \
Materia: **Laboratorio de Aprendizaje Estadístico** \
Tipo de Trabajo: **Clase**

---

## Ejercicio de Codificación

### Carga de Dataframe

In [203]:
import pandas as pd

df = pd.read_excel('Datasets/Aguas_el_feo.xlsx', sheet_name='Sheet1', header=0)

df

        Sabor  Tamaño Hielo  Calificacion
0     naranja   chica    si           8.5
1     naranja   chica    no           7.0
2     naranja  grande    si           9.0
3     naranja  grande    no           7.5
4        coco   chica    si           7.5
5        coco   chica    no           6.0
6        coco  grande    si           8.0
7        coco  grande    no           7.0
8      kahlua   chica    si           9.0
9      kahlua   chica    no           8.0
10     kahlua  grande    si          10.0
11     kahlua  grande    no           8.5
12  fresapiña   chica    si           8.5
13  fresapiña   chica    no           7.0
14  fresapiña  grande    si           9.0
15  fresapiña  grande    no           6.0
16     sandia   chica    si           7.0
17     sandia   chica    no           5.0
18     sandia  grande    si           7.5
19     sandia  grande    no           6.0

### Renombramiento de observaciones

Las variables categóricas de tipo ordinal y booleanas al tener un orden y ser binarias respectivamente, se les puede asignar un valor númerico que respeten ese orden para las que tienen orden y asignar 0-1 para las booleanas.

In [204]:
df['Tamaño'] = df['Tamaño'].map({'chica': 0, 'grande': 1})
df['Hielo'] = df['Hielo'].map({'no': 0, 'si': 1})
df

        Sabor  Tamaño  Hielo  Calificacion
0     naranja       0      1           8.5
1     naranja       0      0           7.0
2     naranja       1      1           9.0
3     naranja       1      0           7.5
4        coco       0      1           7.5
5        coco       0      0           6.0
6        coco       1      1           8.0
7        coco       1      0           7.0
8      kahlua       0      1           9.0
9      kahlua       0      0           8.0
10     kahlua       1      1          10.0
11     kahlua       1      0           8.5
12  fresapiña       0      1           8.5
13  fresapiña       0      0           7.0
14  fresapiña       1      1           9.0
15  fresapiña       1      0           6.0
16     sandia       0      1           7.0
17     sandia       0      0           5.0
18     sandia       1      1           7.5
19     sandia       1      0           6.0

Para variables no ordinales se crea una columna por cada valor único dandole valor de 1 a la fila en la que pertenecía y 0 el resto

In [205]:
df['Naranja'] = df["Sabor"].str.contains("naranja")
df['Coco'] = df["Sabor"].str.contains("coco")
df['Kahlua'] = df["Sabor"].str.contains("kahlua")
df['FresaPiña'] = df["Sabor"].str.contains("fresapiña")
df['Sandia'] = df["Sabor"].str.contains("sandia")
df = df.drop(columns=['Sabor'])

### Regresión Multiple con StastsModels / OLS

In [206]:
import statsmodels.api as sm

df[['Naranja', 'Coco', 'Kahlua', 'FresaPiña', 'Sandia']] = df[['Naranja', 'Coco', 'Kahlua', 'FresaPiña', 'Sandia']].astype(int)
X = df[['Tamaño', 'Hielo', 'Naranja', 'Coco', 'Kahlua', 'FresaPiña', 'Sandia']]
X = sm.add_constant(X)
Y = df['Calificacion']

ols = sm.OLS(Y, X).fit()
ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           Calificacion   R-squared:                       0.927
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     27.67
Date:                Thu, 03 Sep 2026   Prob (F-statistic):           1.11e-06
Time:                        17:37:29   Log-Likelihood:                -6.3060
No. Observations:                  20   AIC:                             26.61
Df Residuals:                      13   BIC:                             33.58
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.4583      0.133     41.111      0.000       5.171       5.745
Tamaño         0.5000      0.184      2.718      0.018       0.103       0.897
Hielo          1.6000      0.184      8.697      0.000       1.203       1.997
Naranja        1.4917      0.186      8.025      0.000       1.090       1.893
Coco           0.6167      0.186      3.318      0.006       0.215       1.018
Kahlua         2.3667      0.186     12.732      0.000       1.965       2.768
FresaPiña      1.1167      0.186      6.007      0.000       0.715       1.518
Sandia        -0.1333      0.186     -0.717      0.486      -0.535       0.268
==============================================================================
Omnibus:                       15.683   Durbin-Watson:                   2.372
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               15.836
Skew:                          -1.542   Prob(JB):                     0.000364
Kurtosis:                       6.081   Cond. No.                     1.77e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.13e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

### Uso de SKlearn para transformación de variables (Ingeniería de Características)

In [ ]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

df_sk = pd.read_excel('Datasets/Aguas_el_feo.xlsx', sheet_name='Sheet1', header=0)

enc = OrdinalEncoder(categories=[['chica', 'grande'], ['no', 'si']])
df_sk[['Tamaño', 'Hielo']] = enc.fit_transform(df_sk[['Tamaño', 'Hielo']])

one_hot_enc = OneHotEncoder(categories=[['naranja', 'coco', 'kahlua', 'fresapiña', 'sandia']], sparse_output=False)
df_sk[['Naranja','Coco','Kahlua','FresaPiña','Sandia']] = one_hot_enc.fit_transform(df_sk[['Sabor']])
df_sk.drop(columns=['Sabor'], inplace=True)
df_sk

    Tamaño  Hielo  Calificacion  Naranja  Coco  Kahlua  FresaPiña  Sandia
0      0.0    1.0           8.5      1.0   0.0     0.0        0.0     0.0
1      0.0    0.0           7.0      1.0   0.0     0.0        0.0     0.0
2      1.0    1.0           9.0      1.0   0.0     0.0        0.0     0.0
3      1.0    0.0           7.5      1.0   0.0     0.0        0.0     0.0
4      0.0    1.0           7.5      0.0   1.0     0.0        0.0     0.0
5      0.0    0.0           6.0      0.0   1.0     0.0        0.0     0.0
6      1.0    1.0           8.0      0.0   1.0     0.0        0.0     0.0
7      1.0    0.0           7.0      0.0   1.0     0.0        0.0     0.0
8      0.0    1.0           9.0      0.0   0.0     1.0        0.0     0.0
9      0.0    0.0           8.0      0.0   0.0     1.0        0.0     0.0
10     1.0    1.0          10.0      0.0   0.0     1.0        0.0     0.0
11     1.0    0.0           8.5      0.0   0.0     1.0        0.0     0.0
12     0.0    1.0           8.5      0.0   0.0     0.0        1.0     0.0
13     0.0    0.0           7.0      0.0   0.0     0.0        1.0     0.0
14     1.0    1.0           9.0      0.0   0.0     0.0        1.0     0.0
15     1.0    0.0           6.0      0.0   0.0     0.0        1.0     0.0
16     0.0    1.0           7.0      0.0   0.0     0.0        0.0     1.0
17     0.0    0.0           5.0      0.0   0.0     0.0        0.0     1.0
18     1.0    1.0           7.5      0.0   0.0     0.0        0.0     1.0
19     1.0    0.0           6.0      0.0   0.0     0.0        0.0     1.0

### Regresión de Comprobación

In [208]:
X = df_sk[['Tamaño', 'Hielo', 'Naranja', 'Coco', 'Kahlua', 'FresaPiña', 'Sandia']]
X = sm.add_constant(X)
Y = df_sk['Calificacion']
ols_sk = sm.OLS(Y, X).fit()
ols_sk.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           Calificacion   R-squared:                       0.927
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     27.67
Date:                Thu, 03 Sep 2026   Prob (F-statistic):           1.11e-06
Time:                        17:39:56   Log-Likelihood:                -6.3060
No. Observations:                  20   AIC:                             26.61
Df Residuals:                      13   BIC:                             33.58
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.4583      0.133     41.111      0.000       5.171       5.745
Tamaño         0.5000      0.184      2.718      0.018       0.103       0.897
Hielo          1.6000      0.184      8.697      0.000       1.203       1.997
Naranja        1.4917      0.186      8.025      0.000       1.090       1.893
Coco           0.6167      0.186      3.318      0.006       0.215       1.018
Kahlua         2.3667      0.186     12.732      0.000       1.965       2.768
FresaPiña      1.1167      0.186      6.007      0.000       0.715       1.518
Sandia        -0.1333      0.186     -0.717      0.486      -0.535       0.268
==============================================================================
Omnibus:                       15.683   Durbin-Watson:                   2.372
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               15.836
Skew:                          -1.542   Prob(JB):                     0.000364
Kurtosis:                       6.081   Cond. No.                     1.77e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.13e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

Los resultados usando ambas maneras para la transformación de variables son exactamente iguales.